[
      {
        id: '1',
        testType: 'Unit',
        serviceName: 'dashboard-service',
        branchName: 'feature/implement_a_UI_for_test_searching',
        buildVersion: 'v0.0.0-SNAPSHOT',
        numTests: 50,
        numRequirements: 30,
        results: {
          passed: 45,
          failed: 2,
          blocked: 1,
          notStarted: 0,
          broken: 1,
          skipped: 1,
          inProgress: 0,
        },
      },
      {
        id: '2',
        testType: 'Integration',
        serviceName: 'PaymentService',
        branchName: 'main',
        buildVersion: 'v1.2.3-RC1',
        numTests: 30,
        numRequirements: 20,
        results: {
          passed: 25,
          failed: 3,
          blocked: 0,
          notStarted: 1,
          broken: 0,
          skipped: 1,
          inProgress: 0,
        },
      },
      {
        id: '3',
        testType: 'Module',
        moduleName: 'AuthModule',
        branchName: 'develop',
        buildVersion: 'v2.0.0-beta',
        numTests: 40,
        numRequirements: 25,
        results: {
          passed: 38,
          failed: 1,
          blocked: 0,
          notStarted: 0,
          broken: 0,
          skipped: 1,
          inProgress: 0,
        },
      },
    ]
